#!/usr/bin/env node

import { readFileSync, writeFileSync } from 'fs'

const colors = readFileSync(new URL('./colors.txt', import.meta.url), 'utf-8')

const variables = []
for (const line of colors.split("\n")) {
  if (!line.trim()) continue
  const [variable] = line.trim().split(":")
  const name = variable!.trim().substring(2)
  variables.push(`--color-${name}: var(--${name});`)
}

const output = `
/* Generated by script/tailwind.ts */
/* Do not edit this file manually */

@theme {
  --color-*: initial;
  ${variables.join("\n  ")}
}
`

writeFileSync(new URL('../src/styles/tailwind/colors.css', import.meta.url), output.trim())
